### ISSUE TITLE
Error in running code under "Connect Tokenizer to a Model"

### ISSUE THREAD

**Issue by gnool** [openvinotoolkit/openvino_tokenizers#188]
As mentioned in title, running the code under the section "Connect Tokenizer to a Model" gives me the error 
Can't set the input tensor with index: 0, because the model input (shape=[?]) and the tensor (shape=()) are incompatible

Any idea how to fix this?

I'm using 2024.2.0

**Comment by gnool** [comment]
The other thing I noticed when combining tokenizer + text encoder models via connect_models is that the final combined model still contains the "attention_mask" as model input.

Concretely, the tokenizer's input is just a string, and outputs attention_mask and input_ids. The input for the text encoder is attention_mask and input_ids, and outputs a vector. After connect_models, I'd have thought that the input is string, and output is a vector, but the input is actually string +  attention_mask. Why did the attention_mask persist as a model input after combination?

**Comment by apaniukov** [comment]
Hi @gnool,
Could you share your model/tokenizer or link to a similar model on HuggingFace Hub so I can reproduce the issue?


> Why did the attention_mask persist as a model input after combination?

It means that the script could not align model inputs automatically. In such cases, you can pass a `name_map` argument `connect_models(..., name_map=[("output_1", "input_1"), ("output_2", "input_2"), ...])` to force a particular alignment between the tokenizer outputs and model inputs.

**Comment by gnool** [comment]
@apaniukov 

The code that was not working is obtained from this repo's README under the section Connect Tokenizer to Model. I've pasted the specific code that I'm referring to below:

```
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from openvino import compile_model, convert_model
from openvino_tokenizers import convert_tokenizer, connect_models

checkpoint = "mrm8488/bert-tiny-finetuned-sms-spam-detection"
hf_tokenizer = AutoTokenizer.from_pretrained(checkpoint)
hf_model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

text_input = ["Free money!!!"]
hf_input = hf_tokenizer(text_input, return_tensors="pt")
hf_output = hf_model(**hf_input)

ov_tokenizer = convert_tokenizer(hf_tokenizer)
ov_model = convert_model(hf_model, example_input=hf_input.data)
combined_model = connect_models(ov_tokenizer, ov_model)
compiled_combined_model = compile_model(combined_model)

openvino_output = compiled_combined_model(text_input)

print(f"OpenVINO logits: {openvino_output['logits']}")
# OpenVINO logits: [[ 1.2007061 -1.4698029]]
print(f"HuggingFace logits {hf_output.logits}")
# HuggingFace logits tensor([[ 1.2007, -1.4698]], grad_fn=<AddmmBackward0>)
```

Running the code above in an environment with OpenVINO 2024.2 (openvino tokenizer is 2024.2 too) gave me

```
Can't set the input tensor with index: 0, because the model input (shape=[?]) and the tensor (shape=()) are incompatible
```

**Comment by apaniukov** [comment]
The script struggled to check the remaining model inputs because they can have multiple names after conversion. The linked PR makes this process more robust.
