### ISSUE TITLE
How to build with Debug mode in Python building

### ISSUE THREAD

**Issue by xczhai** [openvinotoolkit/openvino_tokenizers#287]
as titled.

1. modify the https://github.com/openvinotoolkit/openvino_tokenizers/blob/master/pyproject.toml#L91-L92 can build python with debug?
2. how to build `openvino_tokenizer` with existed local source build openvino for debugging?

**Comment by mryzhov** [comment]
1. Yes, to build tokenizers debug version you would need replace Release with Debug configuration in the toml config. But openvino doesn't support python debug build, and you will face with runtime error on Windows, but for mac and linux it should work. 
2. You would  need to build openvino locally and set OpenVINO_DIR environment variable (e.g for linux/macOS:  export OpenVINO_DIR=<openvino_local_build_dir>.

**Comment by xczhai** [comment]
@mryzhov  Thanks for your help.
summarize it for others.

1. build your local `openvino` runtime;
2. setup local `openvino` runtime env using `source //your/local/path/setupvars.sh`;
3. update `Release` to `Debug` in `//openvino_tokenizer/pyproject.toml`;
4. remove `openvino` version dependency requires in `//openvino_tokenizer/pyproject.toml`;
5. run `pip install --no-deps .`

Possible `fast_tokenizer` downloading issue:
1. download `fast_tokenizer` manually;
2. unzip it in local server;
3. modify the `//openvino_tokenizer/src/CMakeLists.txt`;
```bash
       FetchContent_Declare(
         fast_tokenizer
-        URL      https://bj.bcebos.com/paddlenlp/fast_tokenizer/fast_tokenizer-linux-x64-1.0.2.tgz
-        URL_HASH SHA256=843a8299b55ef2e06ea50ba0d4ab4cb05b9e4cdb7cb8e29f3d55c494a1b7aecc
+        # URL      https://bj.bcebos.com/paddlenlp/fast_tokenizer/fast_tokenizer-linux-x64-1.0.2.tgz
+        # URL_HASH SHA256=843a8299b55ef2e06ea50ba0d4ab4cb05b9e4cdb7cb8e29f3d55c494a1b7aecc
+        SOURCE_DIR /your/local/path/fast_tokenizer
       )
```
